### PR TITLE
reimplement PR #35 on top of #37 (and handle more cases)

### PR DESCRIPTION
**Pull request by jpivarski**
This is a reimplementation that supersedes #35.

### CODE REVIEW

**Comment by jpivarski** [comment]
@lgray, after this goes through, I'll publish uproot-methods 0.4.2.

**Comment by jpivarski** [comment]
@guitargeek Could you test this for your use-case? Thanks!

**Comment by guitargeek** [comment]
Hi! No, unfortunately I get now a `list index out of range` error with this PR. I'll quickly `print`-debug what is happening.

**Comment by jpivarski** [comment]
Thanks; I'll wait to deploy until you get it working. In the meantime, I'll make you a developer so that you can commit directly to this pull request (please only commit to this pull request).

**Comment by jpivarski** [comment]
@lgray: I added you as a collaborator so that you can commit directly to this pull request. I'm not sure if your fixes and @guitargeek's are compatible.

**Comment by guitargeek** [comment]
Hi, ok I see there is some confusion here because we have two issues. Sorry about the `issubclass`, I understand how that might be not working in all usecases now.

The actual issue I tried to fix was the following: the previous `jaggedType` list will always have length one (note the `if starts is None`) so it will always take the type of the first awkward array not the last. Then in the end, you do something for every `i` which is not a `cls.awkward.JaggedArray` unless this is by chance only true for the index 0, you'll get an out of range error.

**Comment by guitargeek** [comment]
Oh and the constructor seems to work, even though I can print-proove that I have the starts-stops from my masked array. Everything would work for me if we'd just fix the issue with the out of range :)

**Comment by jpivarski** [comment]
If you take a `MaskedArray` and ask for `.starts` or pass in `(starts, stops, content)` as constructor arguments, it will raise errors. Those aren't properties of `MaskedArray`, and while its constructor accepts three arguments, the third argument has to be a boolean (`maskedwhen`); it would raise a `TypeError` if given an array.

I'm confused about what's going on here. The `issubclass(type(x), cls)` vs `isinstance(x, cls)` is a matter of style; the other issues are more substantial.

If your new error is "list out of range," it sounds to me like @lgray's PR introduced a new error into your workflow (before or after the previous one, I can't say).

**Comment by guitargeek** [comment]
Yeah I described my new problem in the post above. Wait, I will write a unit test for my usecase then then can see for yourself.

**Comment by jpivarski** [comment]
Okay, thanks.

**Comment by guitargeek** [comment]
Here it is:

```
import uproot_methods
import awkward

counts = [2,2,2]
mask = [True, False, True]

pt = awkward.JaggedArray.fromcounts(counts, [42.71, 31.46, 58.72, 30.19, 47.75, 10.83])
eta = awkward.JaggedArray.fromcounts(counts, [0.54, 1.57, -2.33, -1.22, -2.03, -0.37])
phi = awkward.JaggedArray.fromcounts(counts, [-2.13, 0.65, 2.74, 0.36, 2.87, -0.47])

pt = pt[mask]
eta = eta[mask]
phi = phi[mask]

print(type(pt))

electrons = uproot_methods.TLorentzVectorArray.from_ptetaphim(pt, eta, phi, 0.000511)
```

I added the print statement there to show you that funnily enough, even though I do the mask, you will see it's still an `awkward.array.jagged.JaggedArray` what I have. So that's why the constructor works.

I have no real opinion on the caching though, I'm still at the point where I try to wrap my head around it...

**Comment by jpivarski** [comment]
Okay, you don't have a `MaskedArray`, so it's less complicated than I thought. You have a _masked_ array.  :)

**Comment by jpivarski** [comment]
Your issue is unrelated to the masking (I just tried it without the three `pt = pt[mask]` etc. lines). It's related to the fact that the mass provided in the constructor is a scalar, rather than being a jagged array with the same structure as the other three. I can't remember if this function was supposed to handle that case or not.

**Comment by lgray** [comment]
@guitargeek Given what you're doing, you should come check out https://github.com/CoffeaTeam/fnal-column-analysis-tools, we're looking for more alpha testers or developers and we've solved/worked through many of the problems you're likely to encounter. Let me know if you want to chat further.

**Comment by guitargeek** [comment]
Well it's straight from your example actually, except for the `mask` [1]. You also have a scalar there. I though that was the idea of `normalize`: turn normal numpy arrays and scalars to awkward arrays via broadcasting. 

[1] https://github.com/scikit-hep/awkward-array/blob/master/tests/test_physics.py#L57

**Comment by jpivarski** [comment]
I'm looking at `_normalize_arrays` now (realizing that that's where the exception is occurring, too—it's unrelated to anything in wrap/unwrap caching logic). I just hadn't remembered whether it was supposed to handle this case; apparently, it is, but it's doing it wrong.

**Comment by guitargeek** [comment]
Yes, I have seen that today @lgray, nice talk in xpog! I will definitely contact you soon! Sorry for the off-topic.

**Comment by jpivarski** [comment]
This should be it. Your test works; if you don't have any other tests (and therefore any other commits), I'd like to revert the collaborators list for cleanliness.

@guitargeek and @lgray: you're both done?

**Comment by guitargeek** [comment]
Yep it works! Thanks a lot.

**Comment by lgray** [comment]
@jpivarski @guitargeek Why are we keeping track of only the last encountered type now? You should keep track of each (jagged subtype) type of each input array, no?

**Comment by jpivarski** [comment]
@lgray I reverted that change. Look at the full diff.

**Comment by jpivarski** [comment]
Or, more to the point, I replaced the `append` (which could make `jaggedtypes` get out of sync with `arrays` when not all are `JaggedArrays`) with item assignment, which can't get out of sync and has the correct default. Scalar and flat inputs are promoted to `JaggedArrays`.

**Comment by guitargeek** [comment]
Honestly, I didn't get it :( I thought the type only needs to be determined so you have something to cast the non-awkward types to. If you have different types among the awkward types, it's not clear what to do anyway.

**Comment by jpivarski** [comment]
That's why this had to be carefully merged with the previous PR; that one was all about different types of `JaggedArrays` (some with physics methods attached, some with Numba enhancements). It's necessary to propagate the exact types of every array.

**Comment by guitargeek** [comment]
And with the logic you have now, it will only get the type from the first awkward array it encounters. Afterwards, stops is not None anymore and it will not enter that if.

**Comment by jpivarski** [comment]
You're right! I just put in a fix for that.

**Comment by jpivarski** [comment]
I think we're good! Thanks!

**Pull request merged**
