### PR TITLE
return arrays instead of list copies

### LINKED ISSUE #18: TH1 methods `values`, `variances`, `allvalues`, `allvariances` should return numpy arrays, not lists
These methods currently return copies of internal lists. It would be more convenient and potentially faster to return numpy arrays instead of lists. arrays are faster to allocate and expected in a context of numerical computing.

### PR DESCRIPTION
**Pull request by HDembinski**
Returns arrays instead of lists, closes #18

### CODE REVIEW

**Comment by jpivarski** [comment]
Wait a minute— what am I saying? These arrays are coming out of histograms, which won't live on the GPU because they're mostly Python objects. And especially since this is just wrapping lists as arrays, it has no business being linked to the `awkward.util.numpy` choice.

**Comment by jpivarski** [comment]
Travis burped. I restarted the one test.

**Comment by HDembinski** [comment]
I haven't looked into `awkward.util.numpy`. Having the option to read directly into GPU memory sounds exciting! But keep people like me in mind, who cannot use the GPU... because they bought the wrong graphics card :)

**Comment by jpivarski** [comment]
`awkward.util.numpy` is just a reference to `numpy`, but it's a centralized place to change that reference. `cupy` is the alternative that comes to mind, though there might be others. (`dask.array` wouldn't be a good choice; the operations inside of uproot would be translated into unnecessarily complicated computation graphs that take Dask longer to compute than the single-threaded version.) Swapping to CuPy or any other Numpy replacement would be entirely opt-in.

However, that only makes sense for TTree data. Even if you're running TTree data through a GPU, the arrays generated by the `values` and `variances` almost certainly want to be ordinary Numpy arrays on the CPU. When I swept through uproot for `numpy`/`awkward.util.numpy` consistency, I made only the arrays involved in TTree operations `awkward.util.numpy`, while the rest, like decompressing file buffers or handling histogram data, go straight to `numpy`.

**Pull request merged**
