### PR TITLE
fix missing _fSumw2 field

### LINKED ISSUE #16: TH1 from_numpy does not fill _fSumw2
The `from_numpy` function in TH1.py does not fill the field `_fSumw2`, therefore calling the method `variances()` on a TH1 generated in this way fails with an error.

### PR DESCRIPTION
**Pull request by HDembinski**
Closes #16

### CODE REVIEW

**Comment by jpivarski** [comment]
Note: you're way faster at this than I am. The tidal wave of emails kept me on my train laptop all morning; I'm only now switching over to the desktop to handle all of these fixes.

**Comment by HDembinski** [comment]
Sorry, I just had several things to commit at once :) I am not a particularly fast programmer. You should see me thinking and wondering about boost.histogram code, it takes forever.

**Comment by jpivarski** [comment]
I just saw the barrage of GitHub emails in my inbox and was thinking it would be hard to catch up. But you're on European time, so it was a burst before the end of the work day that I could catch up to. I'm not used to coding in this social media mode— I think I'm supposed to respond to all of these things like a conversation, but I can take it slowly as a queue.

**Comment by HDembinski** [comment]
Yes, that's right.

**Pull request merged**
