### PR TITLE
Add support for Python 3.8 and 3.9

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
While at it, add some tests on Python 3.8, which were missing.

To minimise the amount of tests I dropped them on 3.6. That seems OK at this stage.

Let me know if you fancy more tests.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Not too surprising (I had not checked all dependencies) but numpy==1.13 is a no-go for Python 3.9.  I reckon you could very well require >=1.15, but let me know.

**Review by jpivarski — COMMENTED** [review]
uproot-methods is part of the Awkward 0/Uproot 3 system, which is [being deprecated and will be non-default by December 1](https://indico.cern.ch/event/960587/contributions/4070318/), but that's not reason to include this test.

The cases that are failing are ones that pin a specific NumPy version in Python 3.8 and 3.9. Python 3.9 needs NumPy >= 1.19.3, which came out just last week. There are probably similar constraints between Python 3.8 and some versions of NumPy, but I don't know what they are offhand. We can just exclude the combinations that fail now. (They're failing while trying to compile NumPy; adding `--only-binary=numpy` to the `pip install` would make them fail faster and in more obvious ways.)

**Comment by eduardo-rodrigues** [comment]
> uproot-methods is part of the Awkward 0/Uproot 3 system, which is [being deprecated and will be non-default by December 1](https://indico.cern.ch/event/960587/contributions/4070318/), but that's not reason to include this test.

Right. Better still support uproot 3 & awkward-array for a while, as many will not switch immediately. That's why I think it makes sense to support Python 3.9; and 3.8 as well, BTW.

**Comment by eduardo-rodrigues** [comment]
OK, this is ready modulo a bump in the version towards a patch release. I will wait for your green light to commit the update to `version.py` ...

Once this is done I can make the necessary updates to `uproot` and `awkward-array`.

**Comment by jpivarski** [comment]
Please do update the version number (a new minor version, the "y" in "x.y.z"). I don't think there will be any issues with Awkward 0 and Uproot 3, apart from NumPy version. Given that this doesn't have long to live, we can be merciless in removing things that don't work.

**Comment by eduardo-rodrigues** [comment]
Done bumping up to 0.8.0, @jpivarski.

**Comment by eduardo-rodrigues** [comment]
Kindly make the release when you find the time ... Thanks.

**Comment by jpivarski** [comment]
Right—the release, too—that's a little harder to do from my phone. Let me see...

**Pull request merged**
