### PR TITLE
Fix Y binning and revert TH2.numpy behavior

### LINKED ISSUE #31: Bug -> uproot_methods 0.3.2 does not read in two dimensional histograms correctly
Using uproot 0.3.2 causes the binning of the pt axis for the histogram here to be incorrect:
https://github.com/CoffeaTeam/fnal-column-analysis-tools/blob/master/tests/samples/testSF2d.histo.root

output in uproot 0.3.1 (correct by verifying in ROOT):
```
mac-129479:fnal-column-analysis-tools lagray$ pip install uproot-methods==0.3.1
Collecting uproot-methods==0.3.1
  Using cached https://files.pythonhosted.org/packages/f4/30/de9f8a9d7b380c5a9bcd9177836deccf18ddb9cb88533c8683e02af4bb66/uproot_methods-0.3.1-py2.py3-none-any.whl
Requirement already satisfied: awkward>=0.7.0 in /anaconda2/lib/python2.7/site-packages (from uproot-methods==0.3.1) (0.7.1)
Requirement already satisfied: numpy>=1.13.1 in /anaconda2/lib/python2.7/site-packages (from uproot-methods==0.3.1) (1.15.4)
Installing collected packages: uproot-methods
  Found existing installation: uproot-methods 0.3.2
    Uninstalling uproot-methods-0.3.2:
      Successfully uninstalled uproot-methods-0.3.2
Successfully installed uproot-methods-0.3.1
mac-129479:fnal-column-analysis-tools lagray$ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> hist = uproot.open('tests/samples/testSF2d.histo.root')['scalefactors_Tight_Electron;1']
>>> hist.numpy()
(array([[0.80655736, 0.82857144, 1.0328639 , 1.007752  , 0.94072163,
        0.9458763 , 0.9897698 , 1.0339806 , 0.8274854 , 0.79701495],
       [0.88245934, 0.9274874 , 1.007595  , 0.97203946, 0.9529984 ,
        0.9819967 , 0.9752066 , 0.9748744 , 0.90893763, 0.8633218 ],
       [0.9188406 , 0.9669876 , 0.9881956 , 0.97466666, 0.9534575 ,
        0.97981155, 0.97463286, 0.96638656, 0.95782316, 0.9078014 ],
       [0.9403973 , 0.9809645 , 0.9953917 , 0.97167486, 0.95308644,
        0.9775281 , 0.97893435, 0.9799073 , 0.9685535 , 0.93766236],
       [1.0510856 , 1.0059242 , 1.1041056 , 0.989486  , 0.97549593,
        1.0118906 , 1.010727  , 1.0071633 , 0.9882629 , 1.0213568 ],
       [1.0510856 , 1.0059242 , 1.1041056 , 0.989486  , 0.97549593,
        1.0118906 , 1.010727  , 1.0071633 , 0.9882629 , 1.0213568 ]],
      dtype=float32), (array([-2.5  , -2.   , -1.566, -1.444, -0.8  ,  0.   ,  0.8  ,  1.444,
        1.566,  2.   ,  2.5  ]), array([ 10.,  20.,  35.,  50.,  90., 150., 500.])))
>>> 
```

output in uproot 0.3.2 (second axis is totally wrong):
```
mac-129479:fnal-column-analysis-tools lagray$ pip install uproot-methods==0.3.2
Collecting uproot-methods==0.3.2
  Using cached https://files.pythonhosted.org/packages/d2/e4/8294ce0ead0ecc2b1d42bcb35409c8b9361c25139c1fc2e887494dd2f0f9/uproot_methods-0.3.2-py2.py3-none-any.whl
Requirement already satisfied: awkward>=0.7.0 in /anaconda2/lib/python2.7/site-packages (from uproot-methods==0.3.2) (0.7.1)
Requirement already satisfied: numpy>=1.13.1 in /anaconda2/lib/python2.7/site-packages (from uproot-methods==0.3.2) (1.15.4)
Installing collected packages: uproot-methods
  Found existing installation: uproot-methods 0.3.1
    Uninstalling uproot-methods-0.3.1:
      Successfully uninstalled uproot-methods-0.3.1
Successfully installed uproot-methods-0.3.2
mac-129479:fnal-column-analysis-tools lagray$ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> hist = uproot.open('tests/samples/testSF2d.histo.root')['scalefactors_Tight_Electron;1']
>>> hist.numpy()
(array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.80655736, 0.82857144, 1.0328639 , 1.007752  ,
        0.94072163, 0.9458763 , 0.9897698 , 1.0339806 , 0.8274854 ,
        0.79701495, 0.        ],
       [0.        , 0.88245934, 0.9274874 , 1.007595  , 0.97203946,
        0.9529984 , 0.9819967 , 0.9752066 , 0.9748744 , 0.90893763,
        0.8633218 , 0.        ],
       [0.        , 0.9188406 , 0.9669876 , 0.9881956 , 0.97466666,
        0.9534575 , 0.97981155, 0.97463286, 0.96638656, 0.95782316,
        0.9078014 , 0.        ],
       [0.        , 0.9403973 , 0.9809645 , 0.9953917 , 0.97167486,
        0.95308644, 0.9775281 , 0.97893435, 0.9799073 , 0.9685535 ,
        0.93766236, 0.        ],
       [0.        , 1.0510856 , 1.0059242 , 1.1041056 , 0.989486  ,
        0.97549593, 1.0118906 , 1.010727  , 1.0071633 , 0.9882629 ,
        1.0213568 , 0.        ],
       [0.        , 1.0510856 , 1.0059242 , 1.1041056 , 0.989486  ,
        0.97549593, 1.0118906 , 1.010727  , 1.0071633 , 0.9882629 ,
        1.0213568 , 0.        ],
       [0.        , 1.0510856 , 1.0059242 , 1.1041056 , 0.989486  ,
        0.97549593, 1.0118906 , 1.010727  , 1.0071633 , 0.9882629 ,
        1.0213568 , 0.        ]], dtype=float32), array([  -inf, -2.5  , -2.   , -1.566, -1.444, -0.8  ,  0.   ,  0.8  ,
        1.444,  1.566,  2.   ,  2.5  ,    inf]), array([        -inf,  10.        ,  91.66666667, 173.33333333,
       255.        , 336.66666667, 418.33333333, 500.        ,
                inf]))
>>> 
```

### PR DESCRIPTION
**Pull request by nsmith-**
Fixes #31 
Changes to return type of TH2.numpy should come with a minor version change

### CODE REVIEW

**Comment by lgray** [comment]
Either format is fine to me. So long as it's well advertised. :-)

**Comment by nsmith-** [comment]
@jpivarski to me, nested edges generalizes to n-D better, but since the method is called `numpy` it should probably behave like numpy.  One can always get `edges` and `values` separately.  What about whether to include overflow?

**Comment by jpivarski** [comment]
These methods map onto ROOT histograms, which only go up to 3D. However, even if generalization was an issue, I don't see how unpacking flat vs. nested is different for an unknown number of dimensions:

```python
values, edges = hist.numpy()
```

Gives you `edges` as an array for 1D and a 2- or 3-tuple of arrays for 2D or 3D, regardless of whether the result was flat or nested. I assume this is how you'd want to unpack it. If you know the dimensionality, you'd say

```python
values, xedges, yedges = hist.numpy()
```

for flat and

```python
values, (xedges, yedges) = hist.numpy()
```

for nested. So it's only if you do know the number of dimensions that there's a difference.

It wouldn't be like Numpy to include overflow bins, but following the other conventions, that could be a `hist.allnumpy()` method.

**Comment by nsmith-** [comment]
Works for me, done

**Pull request merged**
